// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaDeControle.Infrastructure.Data;

#nullable disable

namespace SistemaDeControle.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoRelativo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JustificativaId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeArquivoArmazenado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NomeArquivoOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoConteudo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JustificativaId");

                    b.ToTable("anexos", (string)null);
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.AulaAgendada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Disciplina")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<int>("SalaId")
                        .HasColumnType("integer");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("VigenteAte")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenteDesde")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId", "DiaSemana");

                    b.HasIndex("SalaId", "DiaSemana");

                    b.HasIndex("TurmaId", "DiaSemana");

                    b.ToTable("aulas_agendadas", (string)null);
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.Justificativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RegistroFrequenciaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RegistroFrequenciaId")
                        .IsUnique();

                    b.ToTable("justificativas", (string)null);
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Disciplina")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("professores", (string)null);
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.RegistroFrequencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AulaAgendadaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<int>("RegistradoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("RegistradoPorUsuarioId");

                    b.HasIndex("AulaAgendadaId", "Data")
                        .IsUnique();

                    b.ToTable("registros_frequencia", (string)null);
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int?>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("salas", (string)null);
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoLetivo")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nome", "AnoLetivo", "Turno")
                        .IsUnique();

                    b.ToTable("turmas", (string)null);
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.Anexo", b =>
                {
                    b.HasOne("SistemaDeControle.Domain.Entities.Justificativa", "Justificativa")
                        .WithMany("Anexos")
                        .HasForeignKey("JustificativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Justificativa");
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.AulaAgendada", b =>
                {
                    b.HasOne("SistemaDeControle.Domain.Entities.Professor", "Professor")
                        .WithMany("AulasAgendadas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeControle.Domain.Entities.Sala", "Sala")
                        .WithMany("AulasAgendadas")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeControle.Domain.Entities.Turma", "Turma")
                        .WithMany("AulasAgendadas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Sala");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.Justificativa", b =>
                {
                    b.HasOne("SistemaDeControle.Domain.Entities.RegistroFrequencia", "RegistroFrequencia")
                        .WithOne("Justificativa")
                        .HasForeignKey("SistemaDeControle.Domain.Entities.Justificativa", "RegistroFrequenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroFrequencia");
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.RegistroFrequencia", b =>
                {
                    b.HasOne("SistemaDeControle.Domain.Entities.AulaAgendada", "AulaAgendada")
                        .WithMany("RegistrosFrequencia")
                        .HasForeignKey("AulaAgendadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeControle.Domain.Entities.Professor", "Professor")
                        .WithMany("RegistrosFrequencia")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeControle.Domain.Entities.Usuario", "RegistradoPorUsuario")
                        .WithMany("RegistrosRegistrados")
                        .HasForeignKey("RegistradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AulaAgendada");

                    b.Navigation("Professor");

                    b.Navigation("RegistradoPorUsuario");
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.AulaAgendada", b =>
                {
                    b.Navigation("RegistrosFrequencia");
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.Justificativa", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.Professor", b =>
                {
                    b.Navigation("AulasAgendadas");

                    b.Navigation("RegistrosFrequencia");
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.RegistroFrequencia", b =>
                {
                    b.Navigation("Justificativa");
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.Sala", b =>
                {
                    b.Navigation("AulasAgendadas");
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.Turma", b =>
                {
                    b.Navigation("AulasAgendadas");
                });

            modelBuilder.Entity("SistemaDeControle.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("RegistrosRegistrados");
                });
#pragma warning restore 612, 618
        }
    }
}
